# Generated by Django 3.2.8 on 2021-11-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_name',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
