# Generated by Django 3.2.8 on 2021-11-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_with_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cart',
            field=models.ManyToManyField(to='app.Product_with_quantity'),
        ),
    ]
